// Generated from reference registration.js by build-party-data.cjs. No DOM / 3D.
(function(){'use strict';const source=globalThis.RANK_PARTY_DATA,D=source.calculator,P=source.catalog;const slotDefs=[['equip_cloth','服'],['equip_face','顔'],['equip_neck','首'],['equip_back','背中'],['equip_hand','腕'],['equip_foot','足']];const noPatternId=String(P.bodyPatterns.find(r=>r.name==='なし').id);const neutralGrow=Object.entries(D.grows).find(([,g])=>JSON.stringify(g.multipliers)==='[100,100,100,100]'&&JSON.stringify(g.offsets)==='[0,0,0,0]'&&Number(g.evasion)===0)?.[0]||Object.keys(D.grows)[0];
// Expand the two resistance fields omitted by the original head catalog.
for(const [head,rows] of Object.entries(D.headEffects||{})){const all=rows.filter(r=>r.name==='いじょうたいせい').reduce((n,r)=>n+Number(r.value||0),0);if(!all)continue;const status=(D.headResists[head]??={}).status??={};for(const key of ['こうふん','うごけない'])if(!Object.hasOwn(status,key))status[key]=all;}
function merge(target,row){for(const key of ['hp','ap','atk','def','spd','eva'])target[key]=(Number(target[key])||0)+(Number(row?.[key])||0)}
function patternBonus(pattern){const flags=Number(pattern?.flags)>>>0;return{ap:(flags>>>18)&7,evasion:(flags>>>21)&31,positiveElement:(flags>>>6)&15,negativeElement:(flags>>>10)&15,status:(flags>>>14)&15}}
function skillGroupKey(uid){if(!uid)return'';return String(Number.parseInt(String(uid),16))}
function parseEquipment(effects){const add={hp:0,ap:0,atk:0,def:0,spd:0,eva:0};for(const raw of effects){const text=String(raw).normalize('NFKC'),number=Number(text.match(/[+-]\s*(\d+(?:\.\d+)?)/)?.[0]?.replace(/\s/g,''))||0;let key='';if(/さいだいHP/i.test(text))key='hp';else if(/さいだいAP/i.test(text))key='ap';else if(/こうげきりょく/.test(text))key='atk';else if(/ぼうぎょりょく/.test(text))key='def';else if(/すばやさ/.test(text))key='spd';else if(/かいひりつ/.test(text))key='eva';if(key)add[key]+=number}return{add}}
const maximumEffectPatterns=[/^[火氷風土雷水光闇](?:こうげき|攻撃)$/,/^(?:ゴーストバスター|ひっちゅう|かんつう|むてきかんつう|かそく|硬化|逆ギレ|こんじょう|ターゲット|床ダメージ(?:無効|なし)|浮遊)$/,/^(?:HP吸収|攻撃対象|こうげきたいしょう|攻撃回数|こうげきヒット数|特技回数|とくぎヒット数|固定ダメージ|ダメージ|弱点ダメージ|弱点カバー|けいけんち)$/,/^(?:むてき|ガード|はんしゃ|ゴースト状態|オート防御)$/,/^(?:\+・?どく|\+・?ブラインド|\+・?マヒ|\+・?ねむり|\+・?ゆうわく|\+・?きょうふ|\+・?ジャック|\+・?やけど|\+・?みずびたし|\+・?かぜっぴき|\+・?どろだらけ|\+・?かんでん|\+・?しもやけ|\+・?のろい)$/,/^(?:(?:攻撃|防御|素早さ|回避)落とし|こうげきおとし|ぼうぎょおとし|すばやさおとし|かいひおとし)$/,/ボディ$/];
function effectRecord(raw){const text=String(raw||'').normalize('NFKC').trim();if(!text)return null;const presence=text.match(/^(.*?)\s+(あり|なし)$/);if(presence)return{label:presence[1].trim(),value:presence[2]==='あり'?1:0,unit:'',presence:true};const match=text.match(/^(.*?)\s+([+-]?\s*\d+(?:\.\d+)?)\s*(%|倍|ターン|回|人)?$/);if(!match)return{label:text,value:1,unit:'',presence:true};return{label:match[1].trim(),value:Number(match[2].replace(/\s/g,''))||0,unit:match[3]||'',presence:false}}
function effectMaximum(label){if(/^(?:むてき|ガード|はんしゃ|ゴースト状態|オート防御)$/.test(label))return false;return maximumEffectPatterns.some(pattern=>pattern.test(label))}
function effectCap(label){if(/^(?:攻撃対象|こうげきたいしょう)$/.test(label))return 5;if(/^[火氷風土雷水光闇](?:ぞくせい|属性)$/.test(label)||/たいせい$/.test(label))return 9;if(/^(?:ゆうわく|きょうふ|特技封じ)$/.test(label))return 30;if(/^(?:トゲトゲ|AP自動回復|かばう)$/.test(label))return 100;if(/^(?:むてき|ガード|はんしゃ|ゴースト状態|オート防御)$/.test(label))return 10;if(label==='HP自動回復')return 30;if(label==='ゴールド')return 30;return Infinity}
function aggregateEffects(effects,showTotals=false,applyCaps=false){const values=new Map(),loose=[];for(const raw of effects){const record=effectRecord(raw);if(!record)continue;if(record.presence&&record.label===String(raw).normalize('NFKC').trim()&&!/\s(?:あり|なし)$/.test(String(raw))){if(!loose.includes(record.label))loose.push(record.label);continue}const key=`${record.label}\0${record.unit}\0${record.presence?'p':'n'}`,current=values.get(key);if(!current)values.set(key,{...record});else current.value=effectMaximum(record.label)||record.presence?Math.max(current.value,record.value):Number((current.value+record.value).toFixed(10))}const result=[];for(const record of values.values()){const total=record.value,cap=effectCap(record.label);record.value=applyCaps?Math.min(total,cap):total;if(record.presence){if(record.value>0)result.push(`${record.label} あり`);continue}const totalNote=showTotals&&applyCaps&&Number.isFinite(cap)&&total!==record.value?` (合計値${total})`:'';result.push(`${record.label} ${record.value>0?'+':''}${record.value}${record.unit}${totalNote}`)}return[...result,...loose]}
const elementNames=['火','氷','風','土','雷','水','光','闇'],statusNames=['やけど','しもやけ','かぜっぴき','どろだらけ','かんでん','みずびたし','ブラインド','のろい','どく','マヒ','ねむり','とつぜんし','攻撃ダウン','防御ダウン','素早さダウン','回避ダウン','ゆうわく','きょうふ','ふういん','ジャック','こうふん','うごけない','クリティカル'],allStatusNames=new Set(['やけど','しもやけ','かぜっぴき','どろだらけ','かんでん','みずびたし','ブラインド','のろい','どく','マヒ','ねむり','とつぜんし','ゆうわく','きょうふ','ふういん','こうふん','うごけない']),statusDownNames=['攻撃ダウン','防御ダウン','素早さダウン','回避ダウン'];
const solidColours={赤:{耐水:-2,耐火:2,耐やけど:1},橙:{耐風:-2,耐土:2,耐どろだらけ:1},黄:{耐土:-2,耐雷:2,耐かんでん:1},緑:{耐氷:-2,耐風:2,耐かぜっぴき:1},水:{耐火:-2,耐氷:2,耐しもやけ:1},青:{耐雷:-2,耐水:2,耐みずびたし:1},紫:{耐光:-2,耐闇:2,耐のろい:1},白:{耐闇:-2,耐光:2,耐ブラインド:1},金:{耐火:-2,耐闇:-2,耐マヒ:1,ゴールド:10},銀:{耐水:-2,耐雷:-2,耐どく:1,ぼうぎょりょく:50},桃:{属性耐性:-3,耐ゆうわく:1,ゆうわく:4},黒:{耐ねむり:1}};
const lightColours={赤:{耐水:-1,耐火:1,耐やけど:1},橙:{耐風:-1,耐土:1,耐どろだらけ:1},黄:{耐土:-1,耐雷:1,耐かんでん:1},緑:{耐氷:-1,耐風:1,耐かぜっぴき:1},水:{耐火:-1,耐氷:1,耐しもやけ:1},青:{耐雷:-1,耐水:1,耐みずびたし:1},紫:{耐光:-1,耐闇:1,耐のろい:1},白:{耐闇:-1,耐光:1,耐ブラインド:1},金:{耐火:-1,耐闇:-1,耐マヒ:1,ゴールド:10},銀:{耐水:-1,耐雷:-1,耐どく:1,ぼうぎょりょく:50},桃:{属性耐性:-1,耐ゆうわく:1,ゆうわく:4},黒:{耐ねむり:1}};
const strongColours=Object.fromEntries(Object.entries(solidColours).map(([colour,row])=>[colour,Object.fromEntries(Object.entries(row).map(([key,n])=>[key,n===2&&key.startsWith('耐')?3:n>0?n*2:n-1]))]));strongColours.金={耐火:-3,耐闇:-3,耐マヒ:2,ゴールド:30};strongColours.銀={耐水:-3,耐雷:-3,耐どく:2,ぼうぎょりょく:150};strongColours.桃={属性耐性:-2,耐ゆうわく:2,ゆうわく:8};
const spColours={赤:{耐水:2},橙:{耐風:2},黄:{耐土:2},緑:{耐氷:2},水:{耐火:2},青:{耐雷:2},紫:{耐光:2},白:{耐闇:2},黒:{属性耐性:1},金:{ゴールド:10},銀:{ぼうぎょりょく:50},桃:{属性耐性:2,ゆうわく:2}},positiveByColour={赤:'耐火',橙:'耐土',黄:'耐雷',緑:'耐風',水:'耐氷',青:'耐水',紫:'耐闇',白:'耐光'},statusByColour={赤:'耐やけど',橙:'耐どろだらけ',黄:'耐かんでん',緑:'耐かぜっぴき',水:'耐しもやけ',青:'耐みずびたし',紫:'耐のろい',白:'耐ブラインド',金:'耐マヒ',銀:'耐どく',桃:'耐ゆうわく',黒:'耐ねむり'},attackByColour={赤:'火こうげき',水:'氷こうげき',緑:'風こうげき',橙:'土こうげき',黄:'雷こうげき',青:'水こうげき',白:'光こうげき',紫:'闇こうげき'};
function addValues(target,row){for(const[key,n]of Object.entries(row||{}))target[key]=(target[key]||0)+(Number(n)||0)}
function colourName(uid){const raw=P?.bodyColors?.find(x=>String(x.uid)===String(uid))?.name||'';return raw.replace(/^[濃薄]/,'').replace('水色','水').replace('黄色','黄')}
function colourEffects(color1,color2,pattern,ignoreSecondColour=false){if(ignoreSecondColour&&String(color2)!==String(P?.rareColorUid))color2='0';if(String(color1)===String(color2))color2='0';const first=colourName(color1),second=color2==='0'?'なし':colourName(color2),out={};if(second==='なし')addValues(out,solidColours[first]);else if(second==='SP'){addValues(out,solidColours[first]);addValues(out,spColours[first])}else if(first===second)addValues(out,strongColours[first]);else{addValues(out,lightColours[first]);addValues(out,lightColours[second]);if(new Set([first,second]).has('金')&&new Set([first,second]).has('紫')){out.耐闇=(out.耐闇||0)+1;out.耐光=(out.耐光||0)-1}}if(!['なし','SP'].includes(second)){const colours=[...new Set([first,second])],pb=patternBonus(pattern);if(pb.evasion)out.かいひりつ=(out.かいひりつ||0)+pb.evasion;if(pb.positiveElement)for(const colour of colours){const key=positiveByColour[colour];if(key&&(out[key]||0)+(out.属性耐性||0)>0)out[key]=(out[key]||0)+pb.positiveElement}if(pb.status)for(const colour of colours){const key=statusByColour[colour];if(key)out[key]=(out[key]||0)+pb.status}}if(color1!==color2&&first===second&&attackByColour[first]){out[attackByColour[first]]=1;if(first==='紫')out['ゴーストバスター']=1}return out}
function resistances(colourEffect,head,ability0,effects){const out={element:Object.fromEntries(elementNames.map(x=>[x,0])),status:Object.fromEntries(statusNames.map(x=>[x,0]))},mergeRes=row=>{for(const group of ['element','status'])for(const [k,v]of Object.entries(row?.[group]||{}))if(k in out[group])out[group][k]+=Number(v)||0};for(const[name,n]of Object.entries(colourEffect)){if(name==='属性耐性')for(const key of elementNames)out.element[key]+=n;else if(name.startsWith('耐')){const key=name.slice(1);if(key in out.element)out.element[key]+=n;else if(key in out.status)out.status[key]+=n}}mergeRes(D.headResists[head]);mergeRes(D.abilitySetResists[ability0]);for(const raw of effects){const m=String(raw).normalize('NFKC').match(/^(.+?)たいせい\s*([+-]\s*\d+(?:\.\d+)?)$/);if(!m)continue;const n=Number(m[2].replace(/\s/g,''))||0,name=m[1];if(name in out.element)out.element[name]+=n;else if(name in out.status)out.status[name]+=n;else if(name==='ぞくせい')for(const k of elementNames)out.element[k]+=n;else if(name==='いじょう')for(const k of allStatusNames)out.status[k]+=n;else if(name==='ステータスダウン')for(const k of statusDownNames)out.status[k]+=n}for(const group of ['element','status'])for(const key of Object.keys(out[group]))out[group][key]=Math.min(9,Number(out[group][key])||0);return out}
function dataEffects(rows){return(rows||[]).map(row=>{const unit=row.unit||(row.name==='きょうふ'?'%':'');return`${row.name} ${row.presence?(row.value?'あり':'なし'):`${Number(row.value)>0?'+':''}${row.value}${unit}`}`})}
function colourEffectList(row){const labels={属性耐性:'ぞくせいたいせい',かいひりつ:'かいひりつ',ぼうぎょりょく:'ぼうぎょりょく',ゆうわく:'ゆうわく',ゴールド:'ゴールド'};return Object.entries(row).filter(([key,n])=>n&&(!key.startsWith('耐')||true)).map(([key,n])=>{if(key.endsWith('こうげき')||key==='ゴーストバスター')return`${key} あり`;const label=key.startsWith('耐')?`${key.slice(1)}たいせい`:(labels[key]||key),unit=['ゆうわく','ゴールド'].includes(key)?'%':'';return`${label} ${n>0?'+':''}${n}${unit}`})}
function referenceCalculate(input){
const equipment=input.equipment;const ignorePattern=String(input.color1)===String(input.color2)||!input.color2||String(input.color2)==='0'||colourName(input.color2)==='SP';const value=key=>key==='pattern'&&ignorePattern?noPatternId:input[key];const $=id=>({value:id==='reg-level'?input.level:input.ability});const antennaProgression=level=>resolveProgression(input.antenna,level);const activeSetEffects=()=>activeSets(equipment).map(s=>s.effect).filter(Boolean);
const levelNo=Math.min(D.maxLevel,Math.max(1,Number($('reg-level').value)||1));$('reg-level').value=levelNo;const progression=antennaProgression(levelNo),growUid=D.skillGroupGrows?.[skillGroupKey(progression.skillGroupUid)]||neutralGrow,grow=D.grows[growUid],bodyId=value('body'),patternId=value('pattern'),head=value('head'),color1=value('color1'),color2=value('color2')||'0',body=D.bodies[bodyId],pattern=D.patterns[patternId],level=D.levels[String(levelNo)],ability0=$('reg-ability-0').value||'0',ability1='0';if(!grow||!body||!pattern||!level)return null;const flags=Number(grow.flags)||0,result={hp:0,ap:0,atk:0,def:0,spd:0,eva:0},keys=['hp','atk','def','spd'];for(let i=0;i<4;i++){const minimum=Number(level[i*2])||0,scaled=Number(level[i*2+1])||0,bodyPercent=flags&(1<<(i+1))?Number(body.percent?.[i])||100:100,patternPercent=Number(pattern.percent?.[i])||100;result[keys[i]]=Math.floor(scaled*(Number(grow.multipliers?.[i])||0)*bodyPercent*patternPercent/1000000)+(minimum-scaled)+(Number(grow.offsets?.[i])||0)}const additions={hp:0,ap:0,atk:0,def:0,spd:0,eva:0},headStats=D.heads[head]||{},colourEffect=colourEffects(color1,color2,pattern,String(patternId)===noPatternId);merge(additions,D.abilitySets[ability0]);merge(additions,headStats);merge(additions,{def:colourEffect.ぼうぎょりょく||0,eva:colourEffect.かいひりつ||0});if(!(flags&(1<<6)))additions.ap-=Number(headStats.ap)||0;merge(result,additions);const pb=patternBonus(pattern),antenna=progression.step;result.ap=flags&(1<<14)?0:Math.max(0,(Number(antenna?.ap)||0)+pb.ap+additions.ap);result.eva=Math.min(100,Math.max(0,(Number(body.evasion)||0)+(Number(grow.evasion)||0)+additions.eva));const rawEffects=[...slotDefs.flatMap(([slot])=>D.itemEffects[equipment[slot]]||[]),...activeSetEffects()],effects=aggregateEffects(rawEffects),mod=parseEquipment(effects);merge(result,mod.add);result.hp=Math.max(1,result.hp);result.ap=Math.max(0,result.ap);result.atk=Math.max(1,result.atk);result.def=Math.max(1,result.def);result.spd=Math.max(1,result.spd);result.eva=Math.min(100,Math.max(0,result.eva));const effectGroups={head:dataEffects(D.headEffects[head]),colour:colourEffectList(colourEffect),ability:dataEffects(D.abilitySetEffects[ability0]),equipment:effects};return{level:levelNo,result,effects,effectGroups,resistances:resistances(colourEffect,head,ability0,effects),ability0,ability1,equipment:{...equipment},antennaProgression:progression,growUid}}
function activeSets(equipment){const ids=new Set(Object.values(equipment).filter(Boolean));return D.equipmentSets.filter(s=>s.items.length&&s.items.every(i=>ids.has(String(i.uid))));}
function resolveProgression(uid,level){
 const group=source.antennaProgressions.groups.find(g=>g.uid===uid)||null;
 const rank=source.antennaRanks.filter(r=>r.group_uid.toLowerCase()==='0x'+uid&&r.level<=level).at(-1);
 const natural=group?.steps.filter(s=>s.level<=level).at(-1);
 const named=rank&&group?.steps.find(s=>s.skillUid?.toLowerCase()===rank.action_uid.slice(2).toLowerCase());
 const usable=!!rank&&rank.type!=='0x00000001';
 const step=group?{...(named||natural||{}),ap:natural?.ap||0,name:rank?(named?.name||group.firstName):'アンテナのねっこ',skillUid:rank?.action_uid||null,usable}: {...source.antennaProgressions.noAntenna,name:'アンテナなし',usable:false};
 return {group,step,skillGroupUid:uid,rank:rank||null};
}
function calculate(input){const c=referenceCalculate(input);if(!c)throw new Error('個体データを計算できません');c.sets=activeSets(input.equipment);c.totalEffects=aggregateEffects(Object.values(c.effectGroups).flat(),true,true);c.janken=D.headJanken[input.head]||'なし';return c;}
globalThis.RankPartyEngine= {calculate,progression:resolveProgression,activeSets,aggregateEffects,slotDefs};
})();
