(()=>{'use strict';
const C=RankPartyShareCodec,$=id=>document.getElementById(id);let codes=[],page=0,received=null,collection=C.collector(),generation=0,imageEpoch=0,camera=null,cameraEpoch=0,frame=0;
const button=document.createElement('button');button.id='share-button';button.className='secondary';button.textContent='コード・QRで共有';document.querySelector('.toolbar').prepend(button);
const dialog=document.createElement('dialog');dialog.id='share-dialog';dialog.setAttribute('aria-labelledby','share-title');dialog.innerHTML=`<div class="dialog-top"><div><p class="eyebrow">PARTY SHARE</p><h2 id="share-title">パーティを共有・復元</h2></div><button id="share-close" class="icon-button" aria-label="共有画面を閉じる">×</button></div>
<p class="hint">別の端末でこのツールを開き、コードを貼り付けるかQRを読み込んでください。共有情報にはパーティ名・個体名も含まれます。</p>
<section class="share-section"><h3>共有する</h3><label class="field">共有するパーティ<select id="share-scope"><option value="0">味方パーティ</option><option value="1">敵パーティ</option><option value="both">両パーティ</option></select></label><label class="field">共有コード<textarea id="share-output" readonly rows="3" spellcheck="false" aria-label="生成した共有コード"></textarea></label><button id="share-copy" class="secondary">コードをコピー</button><div class="qr-area"><canvas id="share-qr" aria-label="パーティ共有QRコード"></canvas><p id="qr-page"></p><div class="qr-controls"><button id="qr-prev">← 前</button><button id="qr-save">このQRを画像保存</button><button id="qr-next">次 →</button></div><p class="hint">複数枚ある場合は、すべてのQR画像を渡してください。</p></div></section>
<section class="share-section"><h3>コード・QRから復元する</h3><label class="field">共有コード<textarea id="share-input" rows="3" placeholder="RB5. / RB3. などの共有コードを貼り付け" spellcheck="false"></textarea></label><div class="share-actions"><button id="share-paste" class="secondary">コードを貼り付け</button><button id="share-read" class="primary">コードを確認</button><button id="qr-image-button">QR画像を選ぶ</button><button id="qr-camera">カメラで読む</button><button id="qr-reset">読み取りをリセット</button></div><input type="file" id="qr-image" accept="image/*" multiple hidden><video id="qr-video" muted playsinline hidden></video><p id="share-feedback" role="status" aria-live="polite"></p><div id="share-preview" hidden><p id="share-description"></p><label class="field">復元先<select id="share-target"><option value="0">味方パーティを置き換える</option><option value="1">敵パーティを置き換える</option></select></label><p class="hint" id="share-replace-note"></p><button id="share-apply" class="primary">この内容で復元</button></div></section>`;
document.body.append(dialog);
const feedback=(text,error=false)=>{$('share-feedback').textContent=text;$('share-feedback').className=error?'error':'';};
function stopCamera(){cameraEpoch++;cancelAnimationFrame(frame);if(camera)camera.getTracks().forEach(t=>t.stop());camera=null;$('qr-video').srcObject=null;$('qr-video').hidden=true;$('qr-camera').textContent='カメラで読む';}
function resetPreview(){received=null;$('share-preview').hidden=true;}
function draw(){const qr=qrcode(0,'M');qr.addData(codes[page],'Byte');qr.make();const n=qr.getModuleCount(),scale=6,canvas=$('share-qr');canvas.width=canvas.height=(n+8)*scale;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(qr.isDark(y,x))ctx.fillRect((x+4)*scale,(y+4)*scale,scale,scale);$('qr-page').textContent=`QR ${page+1} / ${codes.length}枚`;$('qr-prev').disabled=page===0;$('qr-next').disabled=page===codes.length-1;}
async function generate(){const token=++generation;codes=[];$('qr-save').disabled=true;$('qr-prev').disabled=true;$('qr-next').disabled=true;$('share-qr').hidden=true;$('share-output').value='生成中…';$('share-copy').disabled=true;try{const code=await C.encode(RankPartyApp.getDocument(),$('share-scope').value);if(token!==generation)return;$('share-output').value=code;codes=C.parts(code);page=0;draw();$('qr-save').disabled=false;$('share-qr').hidden=false;$('share-copy').disabled=false;}catch(e){feedback('生成できませんでした：'+e.message,true);}}
button.onclick=()=>{resetPreview();collection=C.collector();feedback('');dialog.showModal();generate();};$('share-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{if(dialog.open)return;generation++;reading++;imageEpoch++;stopCamera();});$('share-scope').onchange=generate;
$('qr-prev').onclick=()=>{if(page>0){page--;draw()}};$('qr-next').onclick=()=>{if(page+1<codes.length){page++;draw()}};
$('share-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('share-output').value);feedback('共有コードをコピーしました。');}catch(e){$('share-output').focus();$('share-output').select();feedback('共有コードを選択しました。端末のコピー操作を使ってください。');}};
$('share-paste').onclick=async()=>{try{if(!navigator.clipboard?.readText)throw Error();const code=await navigator.clipboard.readText();$('share-input').value=code;reading++;resetPreview();feedback(code?'共有コードを貼り付けました。':'クリップボードに文字がありません。',!code);}catch(e){$('share-input').focus();feedback('貼り付けを許可できませんでした。入力欄を長押しして貼り付けてください。',true);}};
$('qr-save').onclick=()=>{const a=document.createElement('a');a.download=`rankbattle-qr-${page+1}-of-${codes.length}.png`;a.href=$('share-qr').toDataURL('image/png');a.click();};
let reading=0;
async function preview(code){const token=++reading;resetPreview();const p=await C.decode(code);if(token!==reading||!dialog.open)return;received=p;stopCamera();$('share-description').textContent=p.map(x=>`${x.name}：${x.members.filter(Boolean).length}人`).join(' / ');$('share-target').disabled=p.length===2;$('share-replace-note').textContent=p.length===2?'味方・敵の両パーティを置き換えます。':'選んだ側の8枠を置き換えます。もう一方は保持します。';$('share-preview').hidden=false;feedback('内容を確認し、復元ボタンを押してください。');}
$('share-input').oninput=()=>{reading++;resetPreview();};$('share-read').onclick=()=>preview($('share-input').value).catch(e=>feedback('復元できません：'+e.message,true));
$('share-apply').onclick=()=>{if(!received)return;try{RankPartyApp.applyShared(received,Number($('share-target').value));dialog.close();}catch(e){feedback(e.message,true);}};
async function accept(text){const result=collection.add(text);feedback(`QRを${result.count} / ${result.total}枚読み取りました。`);if(result.code){$('share-input').value=result.code;await preview(result.code);}}
$('qr-reset').onclick=()=>{reading++;imageEpoch++;stopCamera();collection=C.collector();resetPreview();$('share-input').value='';feedback('読み取りをリセットしました。');};
function decodeCanvas(canvas){const ctx=canvas.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,canvas.width,canvas.height);return jsQR(img.data,img.width,img.height,{inversionAttempts:'attemptBoth'})?.data;}
$('qr-image-button').onclick=()=>$('qr-image').click();$('qr-image').onchange=async event=>{stopCamera();const token=++imageEpoch;try{for(const f of Array.from(event.target.files)){if(f.size>15*1024*1024)throw Error('QR画像は1枚15MB以下にしてください');const bitmap=await createImageBitmap(f);try{if(token!==imageEpoch||!dialog.open)return;const ratio=Math.min(1,1800/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const text=decodeCanvas(canvas);if(!text)throw Error('QRを見つけられませんでした。QR全体が写った明るい画像を選んでください');await accept(text);}finally{bitmap.close();}}}catch(e){feedback(e.message,true);}finally{event.target.value='';}};
$('qr-camera').onclick=async()=>{if(camera){stopCamera();return;}if(!navigator.mediaDevices?.getUserMedia){feedback('この環境ではカメラを利用できません。QR画像を選ぶか、コードを貼り付けてください。',true);return;}const epoch=++cameraEpoch;try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(epoch!==cameraEpoch||!dialog.open){stream.getTracks().forEach(t=>t.stop());return;}camera=stream;const video=$('qr-video');video.hidden=false;video.srcObject=stream;await video.play();$('qr-camera').textContent='カメラを停止';const canvas=document.createElement('canvas');let last=0,lastCode='';async function scan(time){if(epoch!==cameraEpoch||!camera)return;if(time-last>300&&video.readyState>=2){last=time;const r=Math.min(1,1000/video.videoWidth);canvas.width=Math.round(video.videoWidth*r);canvas.height=Math.round(video.videoHeight*r);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);const text=decodeCanvas(canvas);if(text&&text!==lastCode){lastCode=text;try{await accept(text)}catch(e){feedback(e.message,true);}}}if(camera&&epoch===cameraEpoch)frame=requestAnimationFrame(scan);}frame=requestAnimationFrame(scan);}catch(e){stopCamera();feedback('カメラを開始できませんでした。カメラの許可を確認するか、QR画像を選んでください。',true);}};
})();
