(()=>{'use strict';
const D=globalThis.RANK_PARTY_DATA,E=globalThis.RankPartyEngine,M=globalThis.RankPartyModel;
const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function formatEquipmentText(text){return text.replace(/((?:こうげき|ぼうぎょ|すばやさ|かいひ)おとし|(?:攻撃|防御|素早さ|回避)落とし)\s*[+]?([0-9]+)(?:[%％])?/g,(_,name,n)=>`${name} -${Number(n)*10}%`);}
const KEY='rankbattle.parties.tool-v1';let doc=M.empty(),side=0,index=0,undo=null,equipmentSlot='',limit=60,clipboard=null,dragSource=null;
const visual=globalThis.RankAppearance;
const selected=()=>doc.parties[side].members[index];
const bodyDisplayName=name=>{const match=String(name||'').match(/\(([^()]*)\)\s*$/);return match?match[1]:String(name||'体格不明');};
const LIBRARY_KEY='rankbattle.saved-parties.tool-v1';let librarySide=null;
function validateParty(p){const check=M.empty();check.parties[0]=p;return M.validate(check).parties[0];}
function readLibrary(){const rows=JSON.parse(localStorage.getItem(LIBRARY_KEY)||'[]');if(!Array.isArray(rows))throw Error('保存パーティの形式が不正です');return rows.map(validateParty);}
function renderLibrary(){for(let s=0;s<2;s++){const panel=$('saved-parties-'+s);if(!panel)continue;panel.hidden=librarySide!==s;if(panel.hidden)continue;try{const rows=readLibrary();panel.innerHTML=rows.length?rows.map((p,i)=>`<div class="saved-party-row"><button data-party-load="${s}:${i}">${escape(p.name)} <small>（${p.members.filter(Boolean).length}人）</small></button><button class="saved-party-delete" data-saved-delete="${i}" aria-label="${escape(p.name)}を保存一覧から削除">×</button></div>`).join(''):'<p>保存したパーティはありません。</p>';}catch(e){panel.textContent='保存パーティを読み込めません：'+e.message;}}}
function incomplete(){ $('save-state').textContent='入力中 · 名前やレベルを確認してください';$('save-state').className='error'; }
function notice(message,error=false,canUndo=false){$('notice').hidden=false;$('notice').className=error?'error':'';$('notice').textContent=message;if(canUndo){const b=document.createElement('button');b.textContent='元に戻す';b.onclick=()=>{doc=undo;undo=null;persist();render();notice('元に戻しました。')};$('notice').append(b);}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(M.validate(doc)));$('save-state').textContent='● このブラウザーに保存済み';$('save-state').className='';}catch(e){$('save-state').textContent='保存できません · 共有コード・QRで保存してください';$('save-state').className='error';}}
try{const saved=localStorage.getItem(KEY);if(saved)doc=M.validate(JSON.parse(saved));}catch(e){notice('保存データを読み込めませんでした。共有コード・QRからパーティを復元してください。',true);}
// Keep native-ID storage intact; no reverse mapping is distributed to the browser.
try{if(localStorage.getItem('rankbattle.parties.v1')||localStorage.getItem('rankbattle.saved-parties.v1')){
 notice('旧ID形式の保存データが残っています。バックアップを保存し、非公開の移行ツールで専用ID形式へ変換してください。');
 const backup=document.createElement('button');backup.textContent='旧保存データを保存';backup.onclick=()=>{try{
  const value={schema:'rankbattle-legacy-backup',document:JSON.parse(localStorage.getItem('rankbattle.parties.v1')||'null'),savedParties:JSON.parse(localStorage.getItem('rankbattle.saved-parties.v1')||'[]')};
  const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='rankbattle-legacy-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }catch(e){notice('旧保存データを保存できません：'+e.message,true);}};$('notice').append(backup);
}}catch(e){notice('ブラウザーの保存領域を利用できません。共有コードで保存してください。',true);}
outer:for(let s=0;s<2;s++)for(let i=0;i<8;i++)if(doc.parties[s].members[i]){side=s;index=i;break outer;}
const itemName=(slot,uid)=>D.slots[slot].find(r=>r.uid===uid)?.name||'装備なし';
const copiedSlots=new Map();
function markCopied(s,i){const key=s+':'+i,stamp=Date.now();copiedSlots.set(key,stamp);setTimeout(()=>{if(copiedSlots.get(key)===stamp){copiedSlots.delete(key);renderParties();}},2000);}
let infoRestore=null,scrollEditor=false;
function finishEditorView(){if(infoRestore){document.querySelectorAll('#workspace input,#workspace select,#workspace button,#workspace .editor details,#workspace .equipment-cell').forEach(n=>{if(n.tagName==='DETAILS'||n.classList.contains('equipment-cell'))n.inert=true;else n.disabled=true;});}if(scrollEditor){scrollEditor=false;document.querySelector(infoRestore?'#summary':'.editor')?.scrollIntoView({block:'start',behavior:'auto'});}}
function renderParties(){for(let s=0;s<2;s++){
 const p=doc.parties[s];$('party-'+s).innerHTML=`<header><span class="team-label">${s?'ENEMY':'ALLY'}</span><input class="party-name" aria-label="${s?'敵':'味方'}のパーティ名" maxlength="40" required data-party-name="${s}" value="${escape(p.name)}"><span class="member-count">${p.members.filter(Boolean).length} / 8人</span><button data-party-clear="${s}" aria-label="パーティを一括削除">×</button></header><div class="slots">${p.members.map((c,i)=>{
 const calc=c?E.calculate(c):null,body=c?D.catalog.bodyTypes.find(r=>String(r.id)===String(c.body)):null,head=c?D.catalog.headModels.find(r=>String(r.id)===String(c.head)):null;
 return `<div class="slot-wrap"><button class="slot ${c?'filled':'empty'} ${side===s&&index===i?'selected':''}" data-slot="${s}:${i}" ${c?'draggable="true"':''} aria-label="${s?'敵':'味方'} ${i+1}枠目 ${escape(c?.name||'追加')}" aria-pressed="${side===s&&index===i}"><span class="slot-index">${String(i+1).padStart(2,'0')}</span>${c?`${visual?.character(c)||''}<strong>${escape(c.name)}</strong><small>${escape(calc.antennaProgression.step.name)}</small><small class="slot-traits">${escape(bodyDisplayName(body?.name))}・${escape(head?.name||'頭不明')}</small>`:'<span class="plus">＋</span><span>追加する</span>'}</button><div class="slot-tools">${c?`<button data-member-copy="${s}:${i}" aria-label="個体情報をコピー">${copiedSlots.has(s+':'+i)?'✓':'コピー'}</button>`:''}<button data-member-paste="${s}:${i}" ${clipboard?'':'disabled'}>ペースト</button>${c?`<button data-member-delete="${s}:${i}" aria-label="個体を削除">×</button>`:''}</div></div>`;
 }).join('')}</div>${visual?.party(p)||''}<div class="party-save-tools"><button data-party-save="${s}">保存</button><button data-party-library="${s}" aria-expanded="${librarySide===s}">保存パーティを選択</button></div><div id="saved-parties-${s}" class="saved-parties" hidden></div>`;
}renderLibrary();}
function options(rows,current,key='id'){return rows.map(r=>`<option value="${escape(r[key])}" ${String(r[key])===String(current)?'selected':''}>${escape(r.name)}</option>`).join('');}
function field(label,key,rows,c,idKey='id'){return `<label class="field">${label}<select data-field="${key}" aria-label="${label}">${options(rows,c[key],idKey)}</select></label>`;}
const jankenIconPaths={グー:'個体ステータス_装備_能力_参考用/images/janken/rock.png',チョキ:'個体ステータス_装備_能力_参考用/images/janken/scissors.png',パー:'個体ステータス_装備_能力_参考用/images/janken/paper.png'};
function headField(rows,c){const groups=[['タイプ無し',[]],['グー',[]],['チョキ',[]],['パー',[]]];for(const row of rows){const raw=D.calculator.headJanken[row.id],kind=['グー','チョキ','パー'].includes(raw)?raw:'タイプ無し';groups.find(([name])=>name===kind)[1].push(row);}const current=rows.find(row=>String(row.id)===String(c.head));return `<div class="field head-field"><span>頭の形</span><details class="head-picker"><summary>${visual?.image('head',c.head)||''}<span>${escape(current?.name||'頭を選択')}</span></summary><div class="head-picker-menu">${groups.map(([group,items])=>`<section><h4><span>${group}</span>${jankenIconPaths[group]?`<img src="${jankenIconPaths[group]}" alt="${group}">`:''}</h4><div class="head-options">${items.map(row=>`<button type="button" data-head-value="${escape(row.id)}" class="${String(row.id)===String(c.head)?'selected':''}"><span class="head-thumbnail">${visual?.image('head',row.id)||''}</span><span>${escape(row.name)}</span></button>`).join('')}</div></section>`).join('')}</div></details></div>`;}

function choiceButton(key,row,c,idKey='id'){return `<button type="button" data-choice-field="${key}" data-choice-value="${escape(row[idKey])}" aria-pressed="${String(c[key])===String(row[idKey])}">${visual?.image(key==='color1'||key==='color2'?'color':key,row[idKey],c.level)||''}<span>${escape(row.name)}</span></button>`;}
function gridField(label,key,rows,c){return `<div class="field choice-field"><span>${label}</span><details class="choice-picker"><summary>${visual?.image(key,c[key],c.level)||''}${escape(rows.find(r=>String(r.id)===String(c[key]))?.name||'選択')}</summary><div class="choice-menu body-options">${rows.map(r=>choiceButton(key,r,c)).join('')}</div></details></div>`;}
function colorField(key,c){const none=D.catalog.bodyPatterns.find(r=>r.name==='なし'),plain=String(c.pattern)===String(none.id),special=[{uid:'0',name:'なし'},...D.catalog.bodyColors.filter(r=>r.name==='SP')],colors=D.catalog.bodyColors.filter(r=>r.name!=='SP'),rows=key==='color2'&&plain?special:colors,current=[...special,...colors].find(r=>String(r.uid)===String(c[key]));return `<div class="field choice-field"><span>${key==='color1'?'色1':'色2'}</span><details class="choice-picker"><summary>${visual?.image('color',c[key])||''}${escape(current?.name||'なし')}</summary><div class="choice-menu color-options">${key==='color2'&&plain?rows.map(r=>choiceButton(key,r,c,'uid')).join(''):colors.filter(r=>!r.name.startsWith('濃')&&!r.name.startsWith('薄')).map(base=>`<div class="color-choice-row"><img src="images/body-color/${encodeURIComponent(base.name)}.png" alt=""><div>${[base.name,'濃'+base.name,'薄'+base.name].map(name=>choiceButton(key,colors.find(r=>r.name===name),c,'uid')).join('')}</div></div>`).join('')}</div></details></div>`;}
function patternField(c){const ranks={C:['ツートン','ストライプ','ボーダー','斜めボーダー','水玉','アニマル'],B:['シェブロン','ギンガムチェック','バブルドット','ダイヤ','スペード','鱗文'],A:['マーブル','レンガ','スプラッシュ','ピンドット','しずく','うろこ','ヘビ'],S:['トラ','花','星']},rows=D.catalog.bodyPatterns;return `<div class="field"><span>柄</span><details class="choice-picker"><summary>${visual?.image('pattern',c.pattern)||''}${escape(rows.find(r=>String(r.id)===c.pattern)?.name)}</summary><div class="choice-menu"><div class="visual-choice-grid">${rows.filter(r=>r.name==='なし').map(r=>choiceButton('pattern',r,c)).join('')}</div>${Object.entries(ranks).map(([rank,names])=>`<h4>${rank}</h4><div class="visual-choice-grid">${names.map(name=>choiceButton('pattern',rows.find(r=>r.name===name),c)).join('')}</div>`).join('')}</div></details></div>`;}
function antennaField(c){const groups=[...D.antennaProgressions.groups].sort((a,b)=>a.selectionOrder-b.selectionOrder),categories=[['回復・復活・治療',n=>(n>=2&&n<=10)||n===54],['バフ増強',n=>n>=22&&n<=29],['デバフ弱体',n=>[42,43,44,45,46,47,50,51].includes(n)],['状態異常付与・無敵解除',n=>(n>=30&&n<=41)||[48,49,52,53,79,80].includes(n)],['特殊効果',n=>n>=11&&n<=21],['単体属性攻撃',n=>n>=55&&n<=62],['三体属性攻撃',n=>n>=63&&n<=70],['全体属性攻撃',n=>n>=71&&n<=78],['二属性',n=>n>=81]],row=g=>({id:g.uid,name:g.firstName+(g.name!==g.firstName?' → '+g.name:'')});const current=[{id:D.antennaProgressions.noAntenna.uid,name:'アンテナなし'},...groups.map(row)].find(r=>r.id===c.antenna);return `<div class="field"><span>アンテナ系統</span><details class="choice-picker"><summary data-selected-antenna>${visual?.image('antenna',c.antenna,c.level)||''}${escape(current?.name)}</summary><div class="choice-menu"><div class="visual-choice-grid">${[{id:D.antennaProgressions.noAntenna.uid,name:'アンテナなし'},...groups.filter(g=>g.selectionOrder<=1).map(row)].map(r=>choiceButton('antenna',r,c)).join('')}</div>${categories.map(([label,test])=>`<h4>${label}</h4><div class="visual-choice-grid">${groups.filter(g=>test(g.selectionOrder)).map(row).map(r=>choiceButton('antenna',r,c)).join('')}</div>`).join('')}</div></details></div>`;}
function updateChoice(key,value){const next={...selected(),[key]:value};if(key==='pattern'){const plain=D.catalog.bodyPatterns.find(r=>r.name==='なし'),sp=D.catalog.bodyColors.find(r=>r.name==='SP');if(String(value)===String(plain.id)){if(!['0',String(sp.uid)].includes(String(next.color2)))next.color2='0';}else if(['0',String(sp.uid)].includes(String(next.color2)))next.color2=next.color1;}doc.parties[side].members[index]=M.validateCharacter(next);persist();render();}

function faceImage(row){return row?.rgb?`<span class="face-swatch" style="background:rgb(${row.rgb.join(',')})"></span>`:row?.image?`<img class="choice-art" src="${escape(row.image)}" alt="" loading="lazy">`:'';}
function faceFields(c){const data=globalThis.RANK_FACE_DATA;return `<details class="form-section face-section"><summary class="section-title">顔パーツ</summary><div class="form-grid">${Object.entries(data.fields).map(([key,f])=>{const value=c.face?.[key]??data.defaults[key],current=f.rows.find(r=>r.id===value);return `<div class="field"><span>${f.label}</span><details class="choice-picker"><summary>${faceImage(current)}<span>${escape(current.name)}</span></summary><div class="choice-menu visual-choice-grid">${f.rows.map(r=>`<button type="button" data-face-field="${key}" data-face-value="${r.id}" aria-pressed="${r.id===value}">${faceImage(r)}<span>${escape(r.name)}</span></button>`).join('')}</div></details></div>`;}).join('')}</div></details>`;}
function renderEditor(){const c=selected();if(!c){$('workspace').innerHTML='<div class="empty-workspace"><span class="empty-icon">＋</span><h2>最初の個体を登録しましょう</h2><p>上のパーティの「追加する」を選ぶと、個体と装備を編集できます。</p><p class="muted">Rankbattle用の初期レベルは50です。</p></div>';return;}
 const p=D.catalog,calc=E.calculate(c),groups=[...D.antennaProgressions.groups].sort((a,b)=>a.selectionOrder-b.selectionOrder).map(g=>({id:g.uid,name:g.firstName+(g.name!==g.firstName?' → '+g.name:'')})),bodies=p.bodyTypes.map(r=>({...r,name:bodyDisplayName(r.name)}));
 const jankenOrder={'無し':0,'タイプ無し':0,'グー':1,'チョキ':2,'パー':3},heads=[...p.headModels].sort((a,b)=>(jankenOrder[D.calculator.headJanken[a.id]]??4)-(jankenOrder[D.calculator.headJanken[b.id]]??4));
 const abilities=Object.entries(D.calculator.abilitySetMeta).map(([id,r])=>({id,name:r.label}));
 $('workspace').innerHTML=`<aside id="summary" class="panel summary ${side?'enemy':'ally'}" aria-label="計算結果"></aside><article class="panel editor ${side?'enemy':'ally'}"><header class="panel-header"><div><p>${side?'ENEMY':'ALLY'} / SLOT ${String(index+1).padStart(2,'0')}</p><h2>個体の編集</h2></div></header>
 <section class="form-section"><h3 class="section-title">基本情報 <span>01 / CHARACTER</span></h3><div class="form-grid"><label class="field">名前<input data-field="name" maxlength="40" required value="${escape(c.name)}"></label><label class="field">レベル<input data-field="level" type="number" min="1" max="${D.calculator.maxLevel}" step="1" required value="${c.level}"></label>${antennaField(c)}${field('補正','ability',abilities,c)}</div><div id="antenna-detail"></div></section>
 <section class="form-section"><h3 class="section-title">体格・頭・色 <span>02 / TRAITS</span></h3><div class="form-grid">${gridField('体格','body',bodies,c)}${headField(heads,c)}${colorField('color1',c)}${colorField('color2',c)}${patternField(c)}</div></section>${faceFields(c)}</article>
 <article class="panel gear-panel ${side?'enemy':'ally'}"><header class="panel-header"><div><p>${side?'ENEMY':'ALLY'} / SLOT ${String(index+1).padStart(2,'0')}</p><h2>装備・能力</h2></div></header><section class="form-section"><h3 class="section-title">装備 <span>03 / EQUIPMENT</span><button data-action="clear-equipment">一括削除</button></h3><div id="equipment-grid" class="equipment-grid"></div></section><section id="effects-summary" class="form-section effects-summary"></section></article>`;
 renderEquipment();renderSummary(calc);finishEditorView();
}
function renderEquipment(){const c=selected();if(!c)return;const order=['equip_cloth','equip_face','equip_neck','equip_hand','equip_back','equip_foot'],defs=new Map(E.slotDefs),icons={equip_cloth:'cloth.png',equip_face:'face.png',equip_neck:'neck.png',equip_hand:'hand.png',equip_back:'back.png',equip_foot:'foot.png'},slotIcon=slot=>`<img class="equipment-slot-icon" src="images/equipment-slot-icons/${icons[slot]}" alt="" loading="lazy">`;$('equipment-grid').innerHTML=order.map(slot=>{const label=defs.get(slot);return`<div class="equipment-cell" data-equipment="${slot}" role="button" tabindex="0" aria-label="${label}の装備を選ぶ"><div class="equipment-slot-heading">${slotIcon(slot)}<span>${label}</span></div><span class="equipment-art">${visual?.image('equipment',c.equipment[slot])||''}</span><div class="equipment-copy"><div class="equipment-pick"><span>${escape(itemName(slot,c.equipment[slot]))}</span></div><div class="equipment-effect">${escape(formatEquipmentText((D.calculator.itemEffects[c.equipment[slot]]||[]).join(' / ')))}</div></div>${c.equipment[slot]?`<button class="clear" data-clear="${slot}" aria-label="${label}の装備を外す">×</button>`:''}</div>`;}).join('');}
function renderSummary(calc=selected()?E.calculate(selected()):null){if(!calc||!$('summary'))return;
 const c=selected(),a=calc.antennaProgression.step;
 $('antenna-detail').innerHTML=`<div class="antenna-detail"><b>${escape(a.name)}${a.usable?'':' · 戦闘用の技なし'}</b>${escape(a.description||'')}${a.usable?`<br>最大AP ${calc.result.ap}`:''}</div>`;
 const statusOrder=['どく','やけど','しもやけ','かぜっぴき','どろだらけ','かんでん','みずびたし','ブラインド','のろい','とつぜんし','マヒ','ねむり','ゆうわく','きょうふ','ジャック','ふういん','こうふん','うごけない','攻撃ダウン','防御ダウン','素早さダウン','回避ダウン','クリティカル'];
 const RI=globalThis.DENPA_RESISTANCE_ICONS||{},downIcons={'攻撃ダウン':'conditions/status-condition-23.webp','防御ダウン':'conditions/status-condition-25.webp','素早さダウン':'conditions/status-condition-27.webp','回避ダウン':'conditions/status-condition-29.webp'},icon=(name,group)=>{if(group==='status'&&['こうふん','うごけない','クリティカル'].includes(name))return'';let path=group==='element'?RI.attributes?.[name]:downIcons[name]||((name==='ゆうわく')?RI.conditionByName?.みりょう:(name==='ふういん')?'conditions/status-condition-17.webp':RI.conditionByName?.[name]);return path?`<img src="個体ステータス_装備_能力_参考用/images/resistance-icons/${path}" alt="" loading="lazy">`:'';};
 const res=(rows,extra='')=>{const entries=extra?statusOrder.filter(k=>Object.hasOwn(rows,k)).map(k=>[k,rows[k]]):Object.entries(rows);return`<div class="res-grid ${extra}">${entries.map(([k,v])=>{const image=icon(k,extra?'status':'element'),label=k==='ゆうわく'?'みりょう':k;return`<div class="res ${v>0?'positive':v<0?'negative':'zero'}">${image?`<i>${image}</i>`:''}<span>${escape(label)}</span><b>${v>0?'+':''}${v}</b></div>`;}).join('')}</div>`;};
 const effectGroups=[/さいだいHP|\bHP\b/i,/さいだいAP|\bAP\b/i,/こうげきりょく|攻撃力/,/ぼうぎょりょく|防御力/,/すばやさ|素早さ/,/かいひりつ|回避率/,/クリティカル|きゅうしょ/,/(?:火|氷|風|土|雷|水|光|闇)こうげき|属性攻撃/,/ぞくせいたいせい|(?:火|氷|風|土|雷|水|光|闇)たいせい/,/いじょうたいせい|ステータスダウンたいせい|(?:どく|やけど|しもやけ|かぜっぴき|どろだらけ|かんでん|みずびたし|ブラインド|のろい|マヒ|ねむり|ゆうわく|きょうふ|ふういん|ジャック)たいせい/,/こうげきおとし|攻撃落とし/,/ぼうぎょおとし|防御落とし/,/すばやさおとし|素早さ落とし/,/かいひおとし|回避落とし/,/どく|やけど|しもやけ|かぜっぴき|どろだらけ|かんでん|みずびたし|ブラインド|のろい|マヒ|ねむり|ゆうわく|きょうふ|ふういん|ジャック/,/ひっちゅう|ゴーストバスター|かんつう|無敵/,/ガード|反射|はんしゃ|トゲトゲ|ボディ|硬化|逆ギレ/,/ヒット数|回数|対象|ターゲット/,/HP自動回復|AP自動回復|復活/,/ゴールド|経験値|ドロップ/];
 const orderedLabels=['さいだいHP','さいだいAP','こうげきりょく','ぼうぎょりょく','すばやさ','かいひりつ','こうげき','こうげきヒット数','攻撃回数','とくぎヒット数','特技回数','こうげきたいしょう','攻撃対象','クリティカル','きゅうしょづき','ひっちゅう','ゴーストバスター','かんつう','むてきかんつう','むてき','ガード','オート防御','はんしゃ','ゴースト状態','かばう','ターゲット','こんじょう','トゲトゲ','硬化','逆ギレ','かそく','HP吸収','HP自動回復','AP自動回復',...['火','氷','風','土','雷','水','光','闇'].flatMap(k=>[k+'こうげき',k+'ぞくせい']),'ぞくせいたいせい',...['火','氷','風','土','雷','水','光','闇'].map(k=>k+'たいせい'),'いじょうたいせい',...statusOrder.map(k=>k+'たいせい'),'ステータスダウンたいせい','こうげきおとし','ぼうぎょおとし','すばやさおとし','かいひおとし',...statusOrder,...statusOrder.map(k=>'+'+k),'ゴールド','けいけんち','ドロップ'];
 const effectLabel=value=>String(value).normalize('NFKC').trim().replace(/\s+(?:[+-]?\s*\d|あり|なし).*$/,'');
 const effectOrder=value=>{const label=effectLabel(value),rank=orderedLabels.indexOf(label);return rank<0?orderedLabels.length:rank;},sortEffects=rows=>[...rows].sort((a,b)=>effectOrder(a)-effectOrder(b)||effectLabel(a).localeCompare(effectLabel(b),'ja')||String(a).localeCompare(String(b),'ja'));
 const list=rows=>rows.length?`<ul class="effect-list">${sortEffects(rows).map(r=>`<li>${escape(formatEquipmentText(r))}</li>`).join('')}</ul>`:'<p class="muted">効果なし</p>';
 const jankenIcon=jankenIconPaths[calc.janken]||'';
 $('summary').innerHTML=`<header class="panel-header"><div><p>STATUS PREVIEW</p><h2>${escape(c.name)}</h2></div>${jankenIcon?`<img class="summary-janken-icon" src="${jankenIcon}" alt="${escape(calc.janken)}">`:''}</header>${visual?.character(c,'summary-appearance')||''}<div class="game-stat-sheet"><div class="game-stat-row antenna-row"><span>アンテナ</span><b>${escape(a.name)}</b></div>${[[['HP','hp'],['AP','ap']],[['攻撃力','atk'],['防御力','def']],[['素早さ','spd'],['回避率','eva']]].map(pair=>`<div class="game-stat-row">${pair.map(([label,k])=>`<div class="game-stat-cell"><span>${label}</span><b data-stat="${k}">${calc.result[k]}${k==='eva'?'<em>%</em>':''}</b></div>`).join('')}</div>`).join('')}</div><div class="summary-content"><h3>属性耐性</h3>${res(calc.resistances.element)}<h3>状態異常耐性</h3>${res(calc.resistances.status,'status-res')}</div>`;
 $('effects-summary').innerHTML=`<h3 class="section-title">総合効果 <span>04 / EFFECTS</span></h3>${list(calc.totalEffects)}<details class="effect-details"><summary>効果の内訳を見る</summary>${[['head','頭'],['colour','色・柄'],['ability','補正'],['equipment','装備（セット込み）']].map(([k,l])=>`<h4>${l}</h4>${list(calc.effectGroups[k])}`).join('')}</details><details class="effect-details" ${calc.sets.length?'open':''}><summary>セット効果 ${calc.sets.length?calc.sets.length+'件発動':'なし'}</summary>${calc.sets.map(s=>`<div class="set-chip">${escape(s.name)}<br><b>${escape(formatEquipmentText(s.effect))}</b></div>`).join('')||'<p class="muted">必要な装備が揃うと反映されます。</p>'}</details>`;
}
function render(){renderParties();renderEditor();}
document.addEventListener('click',event=>{
 for(const picker of document.querySelectorAll?.('.head-picker[open],.choice-picker[open]')??[])if(!picker.contains(event.target))picker.open=false;
 const face=event.target.closest('[data-face-field]');if(face&&selected()){try{const next={...selected(),face:{...globalThis.RANK_FACE_DATA.defaults,...selected().face,[face.dataset.faceField]:face.dataset.faceValue}};doc.parties[side].members[index]=M.validateCharacter(next);persist();render();document.querySelector('.face-section').open=true;}catch(e){notice(e.message,true);}return;}
 const choice=event.target.closest('[data-choice-field]');if(choice&&selected()){try{updateChoice(choice.dataset.choiceField,choice.dataset.choiceValue);}catch(e){notice(e.message,true);}return;}
 const headChoice=event.target.closest('[data-head-value]');if(headChoice&&selected()){const next={...selected(),head:headChoice.dataset.headValue};try{doc.parties[side].members[index]=M.validateCharacter(next);persist();render();}catch(e){notice(e.message,true);}return;}
 const save=event.target.closest('[data-party-save]');if(save){try{const rows=readLibrary();rows.push(validateParty(doc.parties[+save.dataset.partySave]));localStorage.setItem(LIBRARY_KEY,JSON.stringify(rows));renderParties();notice('パーティを保存しました。');}catch(e){notice('保存できません：'+e.message,true);}return;}
 const library=event.target.closest('[data-party-library]');if(library){const s=+library.dataset.partyLibrary;librarySide=librarySide===s?null:s;renderParties();return;}
 const removeSaved=event.target.closest('[data-saved-delete]');if(removeSaved){try{const rows=readLibrary();rows.splice(+removeSaved.dataset.savedDelete,1);localStorage.setItem(LIBRARY_KEY,JSON.stringify(rows));renderLibrary();notice('保存パーティを削除しました。');}catch(e){notice('削除できません：'+e.message,true);}return;}
 const load=event.target.closest('[data-party-load]');if(load){try{const [s,i]=load.dataset.partyLoad.split(':').map(Number),p=readLibrary()[i];if(!p)throw Error('保存パーティが見つかりません');undo=M.clone(doc);doc.parties[s]=M.clone(p);side=s;index=Math.max(0,p.members.findIndex(Boolean));librarySide=null;persist();render();notice('保存パーティを反映しました。',false,true);}catch(e){notice('読み込めません：'+e.message,true);}return;}
 const clearParty=event.target.closest('[data-party-clear]');if(clearParty){undo=M.clone(doc);doc.parties[+clearParty.dataset.partyClear]=M.empty().parties[+clearParty.dataset.partyClear];persist();render();notice('パーティを一括削除しました。',false,true);return;}
 for(const [attr,key] of [['data-member-copy','memberCopy'],['data-member-paste','memberPaste'],['data-member-delete','memberDelete']]){const button=event.target.closest('['+attr+']');if(!button)continue;const [s,i]=button.dataset[key].split(':').map(Number);if(key==='memberCopy'){clipboard=M.clone(doc.parties[s].members[i]);markCopied(s,i);renderParties();notice('装備を含む個体情報をコピーしました。');return;}if(key==='memberPaste'&&!clipboard)return;undo=M.clone(doc);doc.parties[s].members[i]=key==='memberDelete'?null:M.validateCharacter(M.clone(clipboard));side=s;index=i;persist();render();notice(key==='memberDelete'?'個体を削除しました。':'個体を貼り付けました。',false,true);return;}

 const slot=event.target.closest('[data-slot]');if(slot){scrollEditor=true;[side,index]=slot.dataset.slot.split(':').map(Number);if(!selected()){doc.parties[side].members[index]=M.character(`${side?'敵':'味方'} ${index+1}`);persist();}render();return;}
 const action=event.target.closest('[data-action]')?.dataset.action;if(action&&selected()){
  if(action==='clear-equipment'){undo=M.clone(doc);for(const [slot] of E.slotDefs)selected().equipment[slot]='';persist();render();notice('全装備を外しました。',false,true);return;}
 }
 const clear=event.target.closest('[data-clear]');if(clear&&selected()){selected().equipment[clear.dataset.clear]='';persist();renderEquipment();renderSummary();renderParties();return;}
 const equip=event.target.closest('[data-equipment]');if(equip){equipmentSlot=equip.dataset.equipment;limit=60;$('equipment-query').value='';$('equipment-title').textContent=E.slotDefs.find(([s])=>s===equipmentSlot)[1]+'の装備を選ぶ';renderPicker();$('equipment-dialog').showModal();$('equipment-query').focus();return;}
});
document.addEventListener('dragstart',event=>{const slot=event.target.closest?.('[data-slot][draggable="true"]');if(!slot)return;dragSource=slot.dataset.slot;slot.classList.add('dragging');event.dataTransfer?.setData('text/plain',dragSource);if(event.dataTransfer)event.dataTransfer.effectAllowed='move';});
document.addEventListener('dragover',event=>{const slot=event.target.closest?.('[data-slot]');if(!slot||!dragSource)return;event.preventDefault();if(event.dataTransfer)event.dataTransfer.dropEffect='move';document.querySelectorAll('.slot.drag-over').forEach(x=>x.classList.remove('drag-over'));slot.classList.add('drag-over');});
document.addEventListener('drop',event=>{const slot=event.target.closest?.('[data-slot]'),source=dragSource||event.dataTransfer?.getData('text/plain');if(!slot||!source)return;event.preventDefault();const [ss,si]=source.split(':').map(Number),[ts,ti]=slot.dataset.slot.split(':').map(Number);dragSource=null;document.querySelectorAll('.slot.drag-over,.slot.dragging').forEach(x=>x.classList.remove('drag-over','dragging'));if(ss===ts&&si===ti)return;undo=M.clone(doc);const moving=doc.parties[ss].members[si],replaced=doc.parties[ts].members[ti];doc.parties[ts].members[ti]=moving;doc.parties[ss].members[si]=replaced;side=ts;index=ti;persist();render();notice(replaced?'個体の位置を入れ替えました。':'個体を移動しました。',false,true);});
document.addEventListener('dragend',()=>{dragSource=null;document.querySelectorAll('.slot.drag-over,.slot.dragging').forEach(x=>x.classList.remove('drag-over','dragging'));});
document.addEventListener('keydown',event=>{const equip=event.target.closest?.('[data-equipment]');if(equip&&!event.target.closest('[data-clear]')&&(event.key==='Enter'||event.key===' ')){event.preventDefault();equip.click();}});
document.addEventListener('input',event=>{
 const t=event.target;if(t.matches('[data-party-name]')){if(t.checkValidity()&&t.value.trim()){doc.parties[+t.dataset.partyName].name=t.value;persist();}else incomplete();return;}
 if(!t.matches('input[data-field]')||!selected())return;
 const key=t.dataset.field;if(!t.checkValidity()||!t.value.trim()){incomplete();return;}
 const next={...selected(),[key]:key==='level'?Number(t.value):t.value};
 try{doc.parties[side].members[index]=M.validateCharacter(next);persist();renderParties();renderSummary();if(key==='level'){const image=document.querySelector('[data-selected-antenna] .choice-art');if(image)image.src=visual.thumbnail('antenna',next.antenna,next.level);}if(key==='level')for(const img of document.querySelectorAll?.('[data-choice-field="antenna"] .choice-art')??[])img.src=visual.thumbnail('antenna',img.closest('[data-choice-value]').dataset.choiceValue,next.level);}catch(e){notice(e.message,true);}
});
document.addEventListener('change',event=>{
 const t=event.target;if(!t.matches('select[data-field]')||!selected())return;
 const next={...selected(),[t.dataset.field]:t.value};
 try{updateChoice(t.dataset.field,t.value);}catch(e){notice(e.message,true);render();}
});
function renderPicker(){const query=$('equipment-query').value.normalize('NFKC').toLocaleLowerCase().trim(),items=D.slots[equipmentSlot].filter(r=>RankEquipmentSearch.matches(r.name,query)||(r.name+' '+formatEquipmentText((D.calculator.itemEffects[r.uid]||[]).join(' '))).normalize('NFKC').toLocaleLowerCase().includes(query));
 $('equipment-count').textContent=`${items.length}件${items.length>limit?` · ${limit}件を表示`:''}`;
 $('equipment-results').innerHTML=`<button class="equipment-option" data-pick=""><strong>装備なし</strong></button>`+items.slice(0,limit).map(r=>`<button class="equipment-option" data-pick="${r.uid}" aria-pressed="${selected()?.equipment[equipmentSlot]===r.uid}">${visual?.image('equipment',r.uid)||''}<strong>${escape(r.name)}</strong><small>${escape(formatEquipmentText((D.calculator.itemEffects[r.uid]||[]).join(' / ')||'表示用の効果データなし'))}</small></button>`).join('')+(items.length?'':'<p class="muted">一致する装備がありません。別の名前や効果で検索してください。</p>');$('equipment-more').hidden=items.length<=limit;
}
$('equipment-query').oninput=()=>{limit=60;renderPicker()};$('equipment-more').onclick=()=>{limit+=60;renderPicker()};$('close-equipment').onclick=()=>$('equipment-dialog').close();
let equipmentPress=null;
$('equipment-results').addEventListener('pointerdown',event=>{
 const button=event.target.closest('[data-pick]');
 equipmentPress=button?{button,uid:button.dataset.pick,x:event.clientX,y:event.clientY,top:button.getBoundingClientRect().top,cancelled:false}:null;
 if(button&&event.pointerType==='mouse')event.preventDefault();
});
$('equipment-results').addEventListener('pointermove',event=>{if(equipmentPress&&Math.hypot(event.clientX-equipmentPress.x,event.clientY-equipmentPress.y)>12)equipmentPress.cancelled=true;});
$('equipment-results').addEventListener('pointercancel',()=>{if(equipmentPress)equipmentPress.cancelled=true;});
$('equipment-dialog').addEventListener('scroll',()=>{if(equipmentPress)equipmentPress.cancelled=true;},true);
$('equipment-results').onclick=event=>{
 const pressed=equipmentPress;equipmentPress=null;
 let b=event.target.closest('[data-pick]');
 if(event.detail!==0){
  if(!pressed||pressed.cancelled||!pressed.button.isConnected||Math.hypot(event.clientX-pressed.x,event.clientY-pressed.y)>12||Math.abs(pressed.button.getBoundingClientRect().top-pressed.top)>1)return;
  b=document.elementFromPoint(event.clientX,event.clientY)?.closest('[data-pick]');
  if(b!==pressed.button||b.dataset.pick!==pressed.uid)return;
 }
 if(!b||!selected())return;
 selected().equipment[equipmentSlot]=b.dataset.pick;persist();$('equipment-dialog').close();renderEquipment();renderSummary();renderParties();
};
globalThis.RankPartyApp={getDocument:()=>M.clone(infoRestore?.doc??doc),
 showBattleInfo(payload){const battleDoc=M.validate(payload.document),s=Number(payload.side),slot=Number(payload.slot);if(![0,1].includes(s)||!Number.isInteger(slot)||slot<0||slot>7)return;const indices=battleDoc.parties[s].members.flatMap((c,i)=>c?[i]:[]),i=indices[slot];if(i===undefined)return;if(!infoRestore)infoRestore={doc,side,index};doc=battleDoc;side=s;index=i;scrollEditor=true;document.body.classList.add('battle-info-view');render();},
 closeBattleInfo(){if(!infoRestore)return;({doc,side,index}=infoRestore);infoRestore=null;scrollEditor=false;document.body.classList.remove('battle-info-view');render();},applyShared(parties,target){const next=M.clone(doc);if(parties.length===2)next.parties=parties;else next.parties[target]=parties[0];const valid=M.validate(next);undo=M.clone(doc);doc=valid;side=parties.length===2?0:target;index=Math.max(0,doc.parties[side].members.findIndex(Boolean));persist();render();notice('共有されたパーティを復元しました。',false,true);}};
render();
})();
